This notebook implemments the Q-learning algorithm for solving the FrozenLake problem in gym for details about the environemnt go to https://github.com/openai/gym/wiki/FrozenLake-v0

In [1]:
import numpy as np
import gym
import numpy.random as rnd
from numpy.random import rand

In [4]:
def evalute(render=False):
    state = env.reset()
    for t in range(1000):
        if render:
            env.render()
        action = np.argmax(Q[state])
        next_state,rewrad,done,_ = env.step(action)
        if done:
            return rewrad
        state = next_state 

The code is implementation follows the pseudo code in Reinforcement Learning An Introduction second edition by Richard S. Sutton and Andrew G. Barto, chapter 6 section 6.5, the pseudo code is writtent as comments


In [12]:
#Algorithm parameters
lr = 0.35
eps = 1
eps_decay_rate = 0.9981
min_eps = 0.001
#Initialize Q(s, a), for all s 2 S+, a 2 A(s), arbitrarily except that Q(terminal , ·) = 0
episodes = 5000
gamma = 0.98
env = gym.make('FrozenLake-v0')
Q = np.zeros((env.observation_space.n,env.action_space.n))
rewards = []
# Loop for each episode:
for episode in range(episodes):
    # Initialize S
    state = env.reset()
    for t in range(1000):
        # Choose Action A from state S using policy Derived from Q (e.g, eps-greedy policy)
        if rand() <= eps:
            action = rnd.choice([0,1,2,3])
        else:
            action = np.argmax(Q[state])
        # Take action A, and observe the rewrad and next state.
        next_state,rewrad,done,_ = env.step(action)
        # update the Q for the state action pair
        Q[state][action] = Q[state][action] + lr*(rewrad + gamma*np.max(Q[next_state]) 
                                                                - Q[state][action] )
        #S <- S0
        state = next_state
        #until S is terminal
        if done:
            rewards.append(evalute())
            break
    eps *= eps_decay_rate
    if eps < min_eps:
        eps = min_eps
print('Mean reward in the last 100 episode',np.mean(rewards[-100:]))

Mean reward in the last 100 episode 0.75


In [7]:
print(Q)

[[0.41542842 0.26744644 0.33658626 0.27557768]
 [0.19348265 0.10577871 0.17836707 0.40968027]
 [0.22090231 0.20059674 0.19225153 0.38153354]
 [0.15555975 0.06103635 0.11894761 0.33024598]
 [0.44056718 0.22569273 0.22292518 0.38299965]
 [0.         0.         0.         0.        ]
 [0.03020063 0.02793813 0.33268895 0.03793765]
 [0.         0.         0.         0.        ]
 [0.29445611 0.23177873 0.30994566 0.44345223]
 [0.28006028 0.36114243 0.28280261 0.29500555]
 [0.53970906 0.07063541 0.12234974 0.14028933]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.30941267 0.2091671  0.78917739 0.31475544]
 [0.51448782 0.87426774 0.46319612 0.5094364 ]
 [0.         0.         0.         0.        ]]


In [9]:
evalute(True)


SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up

1.0